### ISSUE TITLE
Freshcode needs to reflect correct 0.17 stable version 

### ISSUE THREAD

**Issue by luzpaz** [luzpaz/FreeCAD-dependencies#5]
[![freshcode.club package](https://repology.org/badge/version-for-repo/freshcode/freecad.svg)](https://repology.org/metapackage/freecad/versions)

http://freshcode.club/projects/freecad
Downstream ticket: https://fossil.include-once.org/freshcode/tktview/7a93997c9a4c16f50d46f69c7e9413aa2c7f1ea0

**Comment by luzpaz** [comment]
I may have filed that downstream ticket prematurely. I found this link: http://freshcode.club/submit/freecad and submitted a request to amend the http://freshcode.club/projects/freecad post.

**Comment by luzpaz** [comment]
FYI, there are different ways to autoupdate Freshcode. 
See http://fossil.include-once.org/freshcode/wiki/Autoupdate
Right now it's set to [AutoupdateGithub](http://fossil.include-once.org/freshcode/wiki/AutoupdateGithub) but I'm not sure it's working.

**Comment by prof-milki** [comment]
There's just too little FCc could extract from:

 * https://github.com/FreeCAD/FreeCAD/blob/master/ChangeLog.txt hasn't been updated in years (also not really standard format)
 * https://github.com/FreeCAD/FreeCAD/releases does not list an updated patch version.
      * `<title>0.18_pre</title>` is the only valid [version tag now](https://github.com/FreeCAD/FreeCAD/tags.atom).
      * There hasn't been one before.
      * Hence even GitHub polling was disabled for FreeCAD.
 * https://launchpadlibrarian.net/384293426/freecad_0.17.13541-1ppa3~ubuntu18.04.1_source.changes hasn't anything worthwhile either (but there's no launchpad extractor anyway)
 
And of course freshcode really needs some changes/news. Otherwise it will just note an empty/hidden release. Scanning GitHub is only meant as workaround. Commit logs aren't changelogs ;)

So, the only option is to manually update it once in a while really.

Nonetheless, thanks for reaching out!

**Comment by luzpaz** [comment]
@prof-milki thank you for your reply. It's good to know these things you point out.
FYI, we refer people to our Bugtracker changelog instead of manually maintaining one. 

CC @sgrogan 
hope it's ok to ping you and just have these above points on your radar. Since it may be that we could potentially make our release process more compliant to standards that scripts and scrapers can use and correctly iterate through our project. 
I'm working on a https://frecadweb.org/wiki/Release_checklist and this is one of the tasks I'll add to the checklist. If we can automate such things it would be ideal. If not, it will manually. Thanks for your attention :smile:

**Comment by luzpaz** [comment]
Freshcode has fixed the mistyped release number. Closing ticket
